version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: "exit 0"

  consumer:
    build: .
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    volumes:
      - .:/app
    command: ["bundle", "exec", "./consumer.rb"]
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure:5

  sender:
    build: .
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    volumes:
      - .:/app
    command: ["bundle", "exec", "./sender.rb"]
    depends_on:
      rabbitmq:
        condition: service_healthy
